### PR TITLE
Adds CI for pypi

### PR DESCRIPTION
**Pull request by thomasstruble**
All the secrets are set up in fork https://github.com/thomasstruble/rdchiral but the fork will be mirrored and pull changes from connorcoley/rdchiral.

The pipeline runs when there is a merge into master. The version number in setup.py will have to be changed for the new version to be successfully published.

### CODE REVIEW

**Comment by thomasstruble** [comment]
@mefortunato @connorcoley forgot to add reviewers but could you take a look?

**Comment by mefortunato** [comment]
Looks good to me.

**Review by connorcoley — APPROVED** [review]
Thanks, Thomas!

**Comment by thomasstruble** [comment]
@connorcoley @mefortunato  it can only be merged by someone who has write acess to the repo. So if it looks good one of you merge it

**Pull request merged**
