### PR TITLE
Te patch

### PR DESCRIPTION
**Pull request by itai-levin**
Modified template extraction to improve identification of chiral centers + added test cases

### CODE REVIEW

**Comment by ljn917** [comment]
@itai-levin Could you please split the stylish changes and the actual patch into different commits? It would make me a lot easier to track what are the actual changes. Thanks in advance.

**Comment by thomasstruble** [comment]
Could you also indicate the version of rdkit you developed with?

**Comment by itai-levin** [comment]
> Could you also indicate the version of rdkit you developed with?

I tested using versions 2017.09.1, 2018.09.1, 2019.03.4, 2020.03.2, because I wasn't sure if the issues I was seeing were specific to one version, and I wasn't sure which version had been used to developed rdchiral. If there is a preferred rdkit version that you have been using, I can use that

**Comment by ljn917** [comment]
FYI, the README.md says RDKit (version >= 2019).

**Comment by itai-levin** [comment]
I'll close this request to open a new one without all of the formatting edits

**Pull request closed without merging**
